//! Content-addressed identifiers: [`ContentHash`], [`ChunkId`], [`MachineId`].
//!
//! All three are 32-byte newtypes generated by the [`define_id`] macro so
//! they share the same surface (hex `Display`, `From<[u8; 32]>`,
//! `AsRef<[u8]>`, serde, `Ord`, `Hash`, plus `from_data` and `as_bytes`).

use std::fmt;

use serde::{Deserialize, Serialize};

macro_rules! define_id {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(Clone, Copy, PartialEq, Eq, Hash, Ord, PartialOrd, Serialize, Deserialize)]
        pub struct $name([u8; 32]);

        impl $name {
            /// Create an ID by hashing arbitrary data with BLAKE3.
            pub fn from_data(data: &[u8]) -> Self {
                Self(blake3::hash(data).into())
            }

            /// Return the raw 32-byte representation.
            pub fn as_bytes(&self) -> &[u8; 32] {
                &self.0
            }

            /// Construct from raw bytes (`const`-callable counterpart to `From<[u8; 32]>`).
            pub const fn from_bytes(bytes: [u8; 32]) -> Self {
                Self(bytes)
            }
        }

        impl From<[u8; 32]> for $name {
            fn from(bytes: [u8; 32]) -> Self {
                Self(bytes)
            }
        }

        impl AsRef<[u8]> for $name {
            fn as_ref(&self) -> &[u8] {
                &self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                for byte in &self.0 {
                    write!(f, "{byte:02x}")?;
                }
                Ok(())
            }
        }

        impl fmt::Debug for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}({})", stringify!($name), self)
            }
        }
    };
}

define_id!(
    /// Content-addressed identifier for a whole file: `blake3(file_bytes)`.
    ///
    /// `ContentHash` is the file's identity in Cairn's inventory. Two
    /// byte-identical files share a `ContentHash` (and therefore one
    /// [`Manifest`](crate::Manifest) and all their chunks). A single bit's
    /// difference produces a distinct `ContentHash`.
    ContentHash
);

define_id!(
    /// Content-addressed identifier for a stored chunk: `blake3(stored_bytes)`.
    ///
    /// When a [`ChunkTransform`] is active (e.g. encryption in M11),
    /// `ChunkId` hashes the *post-transform* bytes — the bytes actually
    /// written to the object store. This keeps the store and `has_chunk`
    /// agnostic to whether content is encrypted; the [`Manifest`](crate::Manifest)
    /// still records enough to verify the pre-transform [`ContentHash`].
    ///
    /// [`ChunkTransform`]: ../../cairn_cas/trait.ChunkTransform.html
    ChunkId
);

define_id!(
    /// Identifier for a Cairn machine, equal to the bytes of its ed25519
    /// public (verifying) key.
    ///
    /// Because the `MachineId` *is* the verifying key, no out-of-band key
    /// distribution is needed: any consumer of a [`LogEntry`](crate::LogEntry)
    /// can reconstruct the verifying key directly from the entry's `machine`
    /// field and check the signature.
    MachineId
);

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn content_hash_from_data_deterministic() {
        let a = ContentHash::from_data(b"hello");
        let b = ContentHash::from_data(b"hello");
        assert_eq!(a, b);
    }

    #[test]
    fn different_data_yields_different_id() {
        assert_ne!(
            ContentHash::from_data(b"hello"),
            ContentHash::from_data(b"world")
        );
    }

    #[test]
    fn chunk_and_machine_ids_deterministic() {
        assert_eq!(ChunkId::from_data(b"chunk"), ChunkId::from_data(b"chunk"));
        assert_eq!(
            MachineId::from_data(b"pubkey"),
            MachineId::from_data(b"pubkey")
        );
    }

    #[test]
    fn from_bytes_and_as_bytes_roundtrip() {
        let bytes = [42u8; 32];
        let id = ContentHash::from(bytes);
        assert_eq!(id.as_bytes(), &bytes);
    }

    #[test]
    fn as_ref_returns_32_bytes() {
        let id = ContentHash::from_data(b"x");
        let slice: &[u8] = id.as_ref();
        assert_eq!(slice.len(), 32);
    }

    #[test]
    fn display_is_lowercase_hex_64_chars() {
        let bytes = [
            0x0a, 0x1b, 0x2c, 0x3d, 0x4e, 0x5f, 0x60, 0x71, 0x82, 0x93, 0xa4, 0xb5, 0xc6, 0xd7,
            0xe8, 0xf9, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb,
            0xcc, 0xdd, 0xee, 0xff,
        ];
        let s = ContentHash::from(bytes).to_string();
        assert_eq!(
            s,
            "0a1b2c3d4e5f60718293a4b5c6d7e8f900112233445566778899aabbccddeeff"
        );
        assert_eq!(s.len(), 64);
    }

    #[test]
    fn debug_includes_typename_and_hex() {
        let id = ChunkId::from([0u8; 32]);
        let d = format!("{id:?}");
        assert!(d.starts_with("ChunkId("));
        assert!(d.ends_with(')'));
        assert_eq!(d.len(), "ChunkId(".len() + 64 + 1);
    }

    #[test]
    fn ordering_is_lexicographic_on_bytes() {
        let low = ContentHash::from([0u8; 32]);
        let high = ContentHash::from([0xff; 32]);
        assert!(low < high);
    }

    #[test]
    fn hashable_into_set() {
        let mut s = HashSet::new();
        s.insert(ContentHash::from_data(b"a"));
        s.insert(ContentHash::from_data(b"b"));
        s.insert(ContentHash::from_data(b"a"));
        assert_eq!(s.len(), 2);
    }

    #[test]
    fn postcard_roundtrip_all_three() {
        let c = ContentHash::from_data(b"file");
        let k = ChunkId::from_data(b"chunk");
        let m = MachineId::from([7u8; 32]);

        let bytes = postcard::to_allocvec(&c).unwrap();
        let back: ContentHash = postcard::from_bytes(&bytes).unwrap();
        assert_eq!(c, back);

        let bytes = postcard::to_allocvec(&k).unwrap();
        let back: ChunkId = postcard::from_bytes(&bytes).unwrap();
        assert_eq!(k, back);

        let bytes = postcard::to_allocvec(&m).unwrap();
        let back: MachineId = postcard::from_bytes(&bytes).unwrap();
        assert_eq!(m, back);
    }

    #[test]
    fn from_bytes_const_compiles() {
        const ID: ContentHash = ContentHash::from_bytes([1u8; 32]);
        assert_eq!(ID.as_bytes(), &[1u8; 32]);
    }
}
